### PR TITLE
model version for Potential class is modified

### PR DESCRIPTION
**Pull request by kenko911**
## Summary
The model version of the Potential class is changed from 1 to 2. This prevents the wrong loading of the model.

## Checklist

- [x] Google format doc strings added. Check with `ruff`.
- [x] Type annotations included. Check with `mypy`.
- [x] Tests added for new features/fixes.
- [x] If applicable, new classes/functions/modules have [`duecredit`](https://github.com/duecredit/duecredit) `@due.dcite` decorators to reference relevant papers by DOI ([example](https://github.com/materialsproject/pymatgen/blob/91dbe6ee9ed01d781a9388bf147648e20c6d58e0/pymatgen/core/lattice.py#L1168-L1172))

Tip: Install `pre-commit` hooks to auto-check types and linting before every commit:

```sh
pip install -U pre-commit
pre-commit install
```

### CODE REVIEW

**Comment by janosh** [comment]
@kenko911 What do you need from me?

**Comment by kenko911** [comment]
Hi @janosh, thanks for reporting the error. I just changed the model version and I would like to know if it fixes the error you reported in  #193?

**Comment by janosh** [comment]
@shyuep already fixed the error in [v0.9.0](https://github.com/materialsvirtuallab/matgl/releases/tag/v0.9.0).

**Comment by shyuep** [comment]
@janosh Yes it is fixed. But this is more for future-proofness. We want a proper versioning of model so that the cache invalidation works properly. It is not related to the tests in pymatgen/downstream codes.

**Pull request merged**
