### PR TITLE
AtomRef Updates

### PR DESCRIPTION
**Pull request by lbluque**
A few edits to the `AtomRef` class:

* added `max_z` as optional kwarg for cases where offsets have not been fitted yet.
* Removed all use of `numpy`
* Use `lstsq` instead of explicitly pseudo-inverse
* Made `property_offset` a buffer to avoid errors when running on GPU and with lightning modules
* Save precomputed identity matrix for onehot vectors as buffer.

### CODE REVIEW

**Comment by lbluque** [comment]
The errors have to do with "Bad serialized model". I don't really understand how to fix those.

I also keep getting this error when running pre-commit:
```
error: TOML parse error at line 69, column 3
   |
69 |   "PERF203", # try-except-in-loop
   |   ^^^^^^^^^
Unknown rule selector: `PERF203`
```
Any ideas on how to get rid of it?

**Comment by shyuep** [comment]
I think it is a version of ruff that is the problem for the PERF. For bad serialized model, I think your fork may have cached an old model. Maybe mgl clear --yes command to remove all models first?

**Comment by lbluque** [comment]
Thanks @shyuep ! 

The "bad serialized" error was actually from my changes. I had to do a few things to change it:
- use `strict=False` when using `load_state_dict` in `IOMixin.load`.
- check if `property_offset` is a list or ndarray in `AtomRef` constructure for backcompat with pretrained models.


I also added a raise from the `BaseException` leading to the "Bad serialized" error because otherwise it can be unclear what the error actually is.

Pls have a look and lmk your thoughts

**Comment by shyuep** [comment]
Thanks. I think this is fine. I will merge.

**Pull request merged**
